export const TABLE_REDUCER_UPDATE = 'UPDATE'
export const TABLE_REDUCER_SAVE_ROW = 'TABLE_REDUCER_SAVE_ROW'
export const TABLE_REDUCER_CREATE_ROW = 'TABLE_REDUCER_CREATE_ROW'
// export const TABLE_REDUCER_SAVE_ROW = 'SAVE_ROW'
