export const TABLE_REDUCER_UPDATE = 'UPDATE'
export const TABLE_REDUCER_UPDATE_ROW_BY_ID = 'UPDATE_ROW_BY_ID'
export const TABLE_REDUCER_CREATE_ROW = 'TABLE_REDUCER_CREATE_ROW'
// export const TABLE_REDUCER_SAVE_ROW = 'SAVE_ROW'
